import json
import os

notebook_content = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# EDA Analysis: WLT vs PLT Comparison\n",
    "\n",
    "This notebook performs an Exploratory Data Analysis (EDA) comparing Within Level Term (WLT) and Post Level Term (PLT) policies using the ILEC 2012-2019 mortality dataset.\n",
    "\n",
    "**Key Visualizations:**\n",
    "1. A/E Ratio vs. Duration (by WLT / PLT)\n",
    "2. Death Rate vs. Attained Age (WLT vs. PLT)\n",
    "3. Exposure Count over Duration (Pre/Post PLT)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from collections import defaultdict\n",
    "import warnings\n",
    "\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# Set plot style\n",
    "plt.style.use('seaborn-v0_8-whitegrid')\n",
    "plt.rcParams['figure.figsize'] = (14, 6)\n",
    "plt.rcParams['font.size'] = 12\n",
    "plt.rcParams['axes.titlesize'] = 14\n",
    "plt.rcParams['axes.labelsize'] = 12\n",
    "\n",
    "# File path\n",
    "DATA_PATH = '../data/ILEC_2012_19 - 20240429.txt'\n",
    "CHUNK_SIZE = 500000"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Data Processing\n",
    "\n",
    "We process the data in chunks due to its large size. We aggregate data for three main metrics:\n",
    "- A/E Ratio\n",
    "- Death Rate\n",
    "- Exposure"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Data Aggregation Collectors\n",
    "\n",
    "# 1. AE vs Duration (by WLT/PLT)\n",
    "ae_duration = {'WLT': defaultdict(lambda: {'death_count': 0, 'exp_death': 0}),\n",
    "               'PLT': defaultdict(lambda: {'death_count': 0, 'exp_death': 0})}\n",
    "\n",
    "# 2. Death Rate vs Attained Age (by WLT/PLT)  \n",
    "death_rate_age = {'WLT': defaultdict(lambda: {'death_count': 0, 'policies_exposed': 0}),\n",
    "                  'PLT': defaultdict(lambda: {'death_count': 0, 'policies_exposed': 0})}\n",
    "\n",
    "# 3. Exposure count over duration (Pre/Post PLT)\n",
    "exposure_duration = {'WLT': defaultdict(lambda: {'policies_exposed': 0, 'amount_exposed': 0}),\n",
    "                     'PLT': defaultdict(lambda: {'policies_exposed': 0, 'amount_exposed': 0})}\n",
    "\n",
    "print(\"Starting Chunk-based Processing...\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "chunk_num = 0\n",
    "total_rows = 0\n",
    "wlt_count = 0\n",
    "plt_count = 0\n",
    "\n",
    "for chunk in pd.read_csv(DATA_PATH, sep='\\t', chunksize=CHUNK_SIZE):\n",
    "    chunk_num += 1\n",
    "    total_rows += len(chunk)\n",
    "    \n",
    "    # Process only records with WLT/PLT indicator\n",
    "    for level_type in ['WLT', 'PLT']:\n",
    "        subset = chunk[chunk['SOA_Post_Lvl_Ind'] == level_type]\n",
    "        \n",
    "        if level_type == 'WLT':\n",
    "            wlt_count += len(subset)\n",
    "        else:\n",
    "            plt_count += len(subset)\n",
    "        \n",
    "        if len(subset) == 0:\n",
    "            continue\n",
    "        \n",
    "        # 1. AE vs Duration - using groupby aggregation\n",
    "        duration_grp = subset.groupby('Duration').agg({\n",
    "            'Death_Count': 'sum',\n",
    "            'ExpDth_VBT2015_Cnt': 'sum'\n",
    "        }).reset_index()\n",
    "        \n",
    "        for _, row in duration_grp.iterrows():\n",
    "            d = row['Duration']\n",
    "            ae_duration[level_type][d]['death_count'] += row['Death_Count']\n",
    "            ae_duration[level_type][d]['exp_death'] += row['ExpDth_VBT2015_Cnt']\n",
    "        \n",
    "        # 2. Death Rate vs Attained Age\n",
    "        age_grp = subset.groupby('Attained_Age').agg({\n",
    "            'Death_Count': 'sum',\n",
    "            'Policies_Exposed': 'sum'\n",
    "        }).reset_index()\n",
    "        \n",
    "        for _, row in age_grp.iterrows():\n",
    "            age = row['Attained_Age']\n",
    "            death_rate_age[level_type][age]['death_count'] += row['Death_Count']\n",
    "            death_rate_age[level_type][age]['policies_exposed'] += row['Policies_Exposed']\n",
    "        \n",
    "        # 3. Exposure count over duration\n",
    "        exp_grp = subset.groupby('Duration').agg({\n",
    "            'Policies_Exposed': 'sum',\n",
    "            'Amount_Exposed': 'sum'\n",
    "        }).reset_index()\n",
    "        \n",
    "        for _, row in exp_grp.iterrows():\n",
    "            d = row['Duration']\n",
    "            exposure_duration[level_type][d]['policies_exposed'] += row['Policies_Exposed']\n",
    "            exposure_duration[level_type][d]['amount_exposed'] += row['Amount_Exposed']\n",
    "    \n",
    "    if chunk_num % 10 == 0:\n",
    "        print(f\"  Processed {chunk_num} chunks ({total_rows:,} records)\")\n",
    "\n",
    "print(f\"\\nProcessing Complete!\")\n",
    "print(f\"  Total records: {total_rows:,}\")\n",
    "print(f\"  WLT records: {wlt_count:,}\")\n",
    "print(f\"  PLT records: {plt_count:,}\")\n",
    "print(\"=\" * 60)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Data Preparation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. AE vs Duration\n",
    "ae_data = []\n",
    "for level_type in ['WLT', 'PLT']:\n",
    "    for duration, stats in sorted(ae_duration[level_type].items()):\n",
    "        if stats['exp_death'] > 0:\n",
    "            ae = stats['death_count'] / stats['exp_death']\n",
    "            ae_data.append({\n",
    "                'Duration': duration, \n",
    "                'AE_Ratio': ae, \n",
    "                'Type': level_type,\n",
    "                'Death_Count': stats['death_count'], \n",
    "                'Exp_Death': stats['exp_death']\n",
    "            })\n",
    "ae_df = pd.DataFrame(ae_data)\n",
    "\n",
    "# 2. Death Rate vs Attained Age\n",
    "dr_data = []\n",
    "for level_type in ['WLT', 'PLT']:\n",
    "    for age, stats in sorted(death_rate_age[level_type].items()):\n",
    "        if stats['policies_exposed'] > 0:\n",
    "            death_rate = stats['death_count'] / stats['policies_exposed'] * 1000  # per 1000\n",
    "            dr_data.append({\n",
    "                'Attained_Age': age, \n",
    "                'Death_Rate_per_1000': death_rate, \n",
    "                'Type': level_type,\n",
    "                'Death_Count': stats['death_count'], \n",
    "                'Policies_Exposed': stats['policies_exposed']\n",
    "            })\n",
    "dr_df = pd.DataFrame(dr_data)\n",
    "\n",
    "# 3. Exposure count over duration\n",
    "exp_data = []\n",
    "for level_type in ['WLT', 'PLT']:\n",
    "    for duration, stats in sorted(exposure_duration[level_type].items()):\n",
    "        exp_data.append({\n",
    "            'Duration': duration, \n",
    "            'Policies_Exposed': stats['policies_exposed'],\n",
    "            'Amount_Exposed': stats['amount_exposed'],\n",
    "            'Type': level_type\n",
    "        })\n",
    "exp_df = pd.DataFrame(exp_data)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Visualizations"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Define colors\n",
    "colors = {'WLT': '#2E86AB', 'PLT': '#E94F37'}\n",
    "\n",
    "# Figure 1: AE vs Duration (WLT vs PLT)\n",
    "fig1, ax1 = plt.subplots(figsize=(14, 6))\n",
    "\n",
    "ae_wlt = ae_df[ae_df['Type'] == 'WLT']\n",
    "ae_plt = ae_df[ae_df['Type'] == 'PLT']\n",
    "\n",
    "# Show only duration 1-50 (reasonable range)\n",
    "ae_wlt_f = ae_wlt[(ae_wlt['Duration'] >= 1) & (ae_wlt['Duration'] <= 50)]\n",
    "ae_plt_f = ae_plt[(ae_plt['Duration'] >= 1) & (ae_plt['Duration'] <= 50)]\n",
    "\n",
    "ax1.plot(ae_wlt_f['Duration'], ae_wlt_f['AE_Ratio'], \n",
    "         marker='o', markersize=5, label='WLT (Within Level Term)', \n",
    "         color=colors['WLT'], linewidth=2, alpha=0.9)\n",
    "ax1.plot(ae_plt_f['Duration'], ae_plt_f['AE_Ratio'], \n",
    "         marker='s', markersize=5, label='PLT (Post Level Term)', \n",
    "         color=colors['PLT'], linewidth=2, alpha=0.9)\n",
    "ax1.axhline(y=1.0, color='gray', linestyle='--', alpha=0.7, linewidth=1.5, label='A/E = 1.0 (Expected)')\n",
    "ax1.fill_between(ae_wlt_f['Duration'], ae_wlt_f['AE_Ratio'], 1.0, alpha=0.1, color=colors['WLT'])\n",
    "ax1.fill_between(ae_plt_f['Duration'], ae_plt_f['AE_Ratio'], 1.0, alpha=0.1, color=colors['PLT'])\n",
    "\n",
    "ax1.set_xlabel('Duration (Policy Year)', fontsize=12)\n",
    "ax1.set_ylabel('A/E Ratio (Actual Deaths / Expected Deaths)', fontsize=12)\n",
    "ax1.set_title('A/E Ratio vs Policy Duration: WLT vs PLT Comparison', fontsize=14, fontweight='bold')\n",
    "ax1.legend(loc='upper right', fontsize=10)\n",
    "ax1.set_xlim(0, 51)\n",
    "ax1.set_ylim(0, max(ae_df['AE_Ratio'].max() * 1.1, 2.0))\n",
    "ax1.grid(True, alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Figure 2: Death Rate vs Attained Age (WLT vs PLT)\n",
    "fig2, ax2 = plt.subplots(figsize=(14, 6))\n",
    "\n",
    "dr_wlt = dr_df[dr_df['Type'] == 'WLT']\n",
    "dr_plt = dr_df[dr_df['Type'] == 'PLT']\n",
    "\n",
    "# Show only age 20-90 (reasonable range)\n",
    "dr_wlt_f = dr_wlt[(dr_wlt['Attained_Age'] >= 20) & (dr_wlt['Attained_Age'] <= 90)]\n",
    "dr_plt_f = dr_plt[(dr_plt['Attained_Age'] >= 20) & (dr_plt['Attained_Age'] <= 90)]\n",
    "\n",
    "ax2.plot(dr_wlt_f['Attained_Age'], dr_wlt_f['Death_Rate_per_1000'], \n",
    "         marker='o', markersize=5, label='WLT (Within Level Term)', \n",
    "         color=colors['WLT'], linewidth=2, alpha=0.9)\n",
    "ax2.plot(dr_plt_f['Attained_Age'], dr_plt_f['Death_Rate_per_1000'], \n",
    "         marker='s', markersize=5, label='PLT (Post Level Term)', \n",
    "         color=colors['PLT'], linewidth=2, alpha=0.9)\n",
    "\n",
    "ax2.set_xlabel('Attained Age', fontsize=12)\n",
    "ax2.set_ylabel('Death Rate (per 1,000 Policy-Years)', fontsize=12)\n",
    "ax2.set_title('Mortality Rate vs Attained Age: WLT vs PLT Comparison', fontsize=14, fontweight='bold')\n",
    "ax2.legend(loc='upper left', fontsize=10)\n",
    "ax2.set_xlim(18, 92)\n",
    "ax2.grid(True, alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Figure 3: Exposure Count over Duration (Pre/Post PLT)\n",
    "fig3, (ax3a, ax3b) = plt.subplots(1, 2, figsize=(16, 6))\n",
    "\n",
    "exp_wlt = exp_df[exp_df['Type'] == 'WLT']\n",
    "exp_plt = exp_df[exp_df['Type'] == 'PLT']\n",
    "\n",
    "# Show only duration 1-50\n",
    "exp_wlt_f = exp_wlt[(exp_wlt['Duration'] >= 1) & (exp_wlt['Duration'] <= 50)]\n",
    "exp_plt_f = exp_plt[(exp_plt['Duration'] >= 1) & (exp_plt['Duration'] <= 50)]\n",
    "\n",
    "# Merge for plotting\n",
    "merged_durations = sorted(set(exp_wlt_f['Duration'].tolist() + exp_plt_f['Duration'].tolist()))\n",
    "width = 0.35\n",
    "\n",
    "# 3a: Policies Exposed\n",
    "wlt_policies = []\n",
    "plt_policies = []\n",
    "for d in merged_durations:\n",
    "    wlt_val = exp_wlt_f[exp_wlt_f['Duration'] == d]['Policies_Exposed'].sum()\n",
    "    plt_val = exp_plt_f[exp_plt_f['Duration'] == d]['Policies_Exposed'].sum()\n",
    "    wlt_policies.append(wlt_val / 1e6)\n",
    "    plt_policies.append(plt_val / 1e6)\n",
    "\n",
    "x = np.arange(len(merged_durations))\n",
    "ax3a.bar(x - width/2, wlt_policies, width, label='WLT (Within Level Term)', \n",
    "         color=colors['WLT'], alpha=0.8)\n",
    "ax3a.bar(x + width/2, plt_policies, width, label='PLT (Post Level Term)', \n",
    "         color=colors['PLT'], alpha=0.8)\n",
    "\n",
    "ax3a.set_xlabel('Duration (Policy Year)', fontsize=12)\n",
    "ax3a.set_ylabel('Policies Exposed (Millions)', fontsize=12)\n",
    "ax3a.set_title('Policy Exposure by Duration', fontsize=14, fontweight='bold')\n",
    "ax3a.legend(loc='upper right', fontsize=9)\n",
    "ax3a.set_xticks(x[::5])\n",
    "ax3a.set_xticklabels([d for d in merged_durations[::5]])\n",
    "ax3a.grid(True, alpha=0.3, axis='y')\n",
    "\n",
    "# 3b: Amount Exposed\n",
    "wlt_amounts = []\n",
    "plt_amounts = []\n",
    "for d in merged_durations:\n",
    "    wlt_val = exp_wlt_f[exp_wlt_f['Duration'] == d]['Amount_Exposed'].sum()\n",
    "    plt_val = exp_plt_f[exp_plt_f['Duration'] == d]['Amount_Exposed'].sum()\n",
    "    wlt_amounts.append(wlt_val / 1e12)\n",
    "    plt_amounts.append(plt_val / 1e12)\n",
    "\n",
    "ax3b.bar(x - width/2, wlt_amounts, width, label='WLT (Within Level Term)', \n",
    "         color=colors['WLT'], alpha=0.8)\n",
    "ax3b.bar(x + width/2, plt_amounts, width, label='PLT (Post Level Term)', \n",
    "         color=colors['PLT'], alpha=0.8)\n",
    "\n",
    "ax3b.set_xlabel('Duration (Policy Year)', fontsize=12)\n",
    "ax3b.set_ylabel('Amount Exposed (Trillions $)', fontsize=12)\n",
    "ax3b.set_title('Amount Exposure by Duration', fontsize=14, fontweight='bold')\n",
    "ax3b.legend(loc='upper right', fontsize=9)\n",
    "ax3b.set_xticks(x[::5])\n",
    "ax3b.set_xticklabels([d for d in merged_durations[::5]])\n",
    "ax3b.grid(True, alpha=0.3, axis='y')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Statistical Summary"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"=\" * 60)\n",
    "print(\"EDA Statistical Summary\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "print(\"\\n[1. A/E Ratio Statistics]\")\n",
    "if len(ae_wlt_f) > 0:\n",
    "    print(f\"  WLT Average A/E: {ae_wlt_f['AE_Ratio'].mean():.4f}\")\n",
    "    print(f\"  WLT A/E Range: {ae_wlt_f['AE_Ratio'].min():.4f} ~ {ae_wlt_f['AE_Ratio'].max():.4f}\")\n",
    "    print(f\"  WLT Total Actual Deaths: {ae_wlt_f['Death_Count'].sum():,.0f}\")\n",
    "if len(ae_plt_f) > 0:\n",
    "    print(f\"  PLT Average A/E: {ae_plt_f['AE_Ratio'].mean():.4f}\")\n",
    "    print(f\"  PLT A/E Range: {ae_plt_f['AE_Ratio'].min():.4f} ~ {ae_plt_f['AE_Ratio'].max():.4f}\")\n",
    "    print(f\"  PLT Total Actual Deaths: {ae_plt_f['Death_Count'].sum():,.0f}\")\n",
    "\n",
    "print(\"\\n[2. Death Rate Statistics (per 1,000 Policy-Years)]\")\n",
    "if len(dr_wlt_f) > 0:\n",
    "    print(f\"  WLT Average Death Rate: {dr_wlt_f['Death_Rate_per_1000'].mean():.4f}\")\n",
    "    print(f\"  WLT Death Rate Range: {dr_wlt_f['Death_Rate_per_1000'].min():.4f} ~ {dr_wlt_f['Death_Rate_per_1000'].max():.4f}\")\n",
    "if len(dr_plt_f) > 0:\n",
    "    print(f\"  PLT Average Death Rate: {dr_plt_f['Death_Rate_per_1000'].mean():.4f}\")\n",
    "    print(f\"  PLT Death Rate Range: {dr_plt_f['Death_Rate_per_1000'].min():.4f} ~ {dr_plt_f['Death_Rate_per_1000'].max():.4f}\")\n",
    "\n",
    "print(\"\\n[3. Exposure Statistics]\")\n",
    "wlt_total_pol = exp_wlt['Policies_Exposed'].sum()\n",
    "plt_total_pol = exp_plt['Policies_Exposed'].sum()\n",
    "wlt_total_amt = exp_wlt['Amount_Exposed'].sum()\n",
    "plt_total_amt = exp_plt['Amount_Exposed'].sum()\n",
    "\n",
    "print(f\"  WLT Total Policies Exposed: {wlt_total_pol:,.0f}\")\n",
    "print(f\"  PLT Total Policies Exposed: {plt_total_pol:,.0f}\")\n",
    "print(f\"  WLT Total Amount Exposed: ${wlt_total_amt:,.0f}\")\n",
    "print(f\"  PLT Total Amount Exposed: ${plt_total_amt:,.0f}\")\n",
    "if wlt_total_pol + plt_total_pol > 0:\n",
    "    wlt_pct = wlt_total_pol / (wlt_total_pol + plt_total_pol) * 100\n",
    "    print(f\"  WLT Proportion: {wlt_pct:.1f}%\")\n",
    "    print(f\"  PLT Proportion: {100 - wlt_pct:.1f}%\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

with open('/Users/BF/Development/SOA/code/wlt_plt_eda.ipynb', 'w') as f:
    json.dump(notebook_content, f, indent=4)

print("Notebook created successfully.")
